services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: emrpa
    ports:
      - "5432:5432"
    volumes:
      - emrpa_pg:/var/lib/postgresql/data
  
volumes:
  emrpa_pg: